system_prompt = """
# ROLE:
You are an intelligent knowledge question and answer assistant
# TASK:
Answer the question. If the [Given Documents] do not do not provide helpful information, answer the question with your internal knowledge. Only give me the answer and do not output any other words.
"""

user_prompt = """
# Given documents:
{reference}
# Question: 
{question}
# Your Response:
"""
