system_prompt = """
# ROLE:
You are an intelligent knowledge question and answer assistant
# TASK:
Answer the question based on the "Hints". Only give me the answer and do not output any other words.
# The answer must be a phrase rather than a sentence.
"""

user_prompt = """
# Question: 
{question}
# Hints:
{reference}

# Your Response:
"""
